import 'package:intl/intl.dart';

import '../menstrual_cycle_widget.dart';

/// Default symptoms data
List<Symptoms> defaultSymptomsData = [
  Symptoms(
    categoryId: 1,
    categoryName: "Feelings",
    categoryColor: "FFA500",
    symptomsData: [
      SymptomsData(symptomName: "Sensitive"),
      SymptomsData(symptomName: "Not in control"),
      SymptomsData(symptomName: "Happy"),
      SymptomsData(symptomName: "Frisky"),
      SymptomsData(symptomName: "Mood swings"),
      SymptomsData(symptomName: "Irritated"),
      SymptomsData(symptomName: "Sad"),
      SymptomsData(symptomName: "Tension"),
      SymptomsData(symptomName: "Angry"),
      SymptomsData(symptomName: "Insecure"),
      SymptomsData(symptomName: "Grateful"),
      SymptomsData(symptomName: "Anxiety"),
      SymptomsData(symptomName: "Excited"),
    ],
  ),
  Symptoms(
    categoryId: 2,
    categoryName: "Mind",
    categoryColor: "8B0000",
    symptomsData: [
      SymptomsData(symptomName: "Calm"),
      SymptomsData(symptomName: "Distracted"),
      SymptomsData(symptomName: "Focused"),
      SymptomsData(symptomName: "Depressed"),
      SymptomsData(symptomName: "Confused"),
      SymptomsData(symptomName: "Stressed"),
      SymptomsData(symptomName: "Motivated"),
      SymptomsData(symptomName: "Unmotivated"),
      SymptomsData(symptomName: "Creative"),
      SymptomsData(symptomName: "Productive"),
      SymptomsData(symptomName: "Unproductive"),
    ],
  ),
  Symptoms(
    categoryId: 3,
    categoryName: "Sexual Life",
    categoryColor: "A52A2A",
    symptomsData: [
      SymptomsData(symptomName: "No sex"),
      SymptomsData(symptomName: "Protected sex"),
      SymptomsData(symptomName: "Unprotected sex"),
      SymptomsData(symptomName: "Oral sex"),
      SymptomsData(symptomName: "Anal sex"),
      SymptomsData(symptomName: "Masturbation"),
      SymptomsData(symptomName: "High sex drive"),
      SymptomsData(symptomName: "Neutral sex drive"),
      SymptomsData(symptomName: "Low sex drive"),
      SymptomsData(symptomName: "Sex toys"),
      SymptomsData(symptomName: "Orgasm"),
      SymptomsData(symptomName: "No orgasm"),
    ],
  ),
  Symptoms(
    categoryId: 4,
    categoryName: "Energy",
    categoryColor: "0000FF",
    symptomsData: [
      SymptomsData(symptomName: "Exhausted"),
      SymptomsData(symptomName: "Tried"),
      SymptomsData(symptomName: "OK"),
      SymptomsData(symptomName: "Energetic"),
      SymptomsData(symptomName: "Fully energized"),
    ],
  ),
  Symptoms(
    categoryId: 5,
    categoryName: "Period",
    categoryColor: "FF0000",
    symptomsData: [
      SymptomsData(symptomName: "Light"),
      SymptomsData(symptomName: "Medium"),
      SymptomsData(symptomName: "Heavy"),
      SymptomsData(symptomName: "Super heavy"),
      SymptomsData(symptomName: "Don't know"),
    ],
  ),
  Symptoms(
    categoryId: 6,
    categoryName: "Symptoms",
    categoryColor: "808080",
    symptomsData: [
      SymptomsData(symptomName: "Everything well"),
      SymptomsData(symptomName: "Cramps"),
      SymptomsData(symptomName: "Tender breasts"),
      SymptomsData(symptomName: "Headache"),
      SymptomsData(symptomName: "Acne"),
      SymptomsData(symptomName: "Backache"),
      SymptomsData(symptomName: "Abdominal pain"),
      SymptomsData(symptomName: "Fatigue"),
    ],
  ),
  Symptoms(
    categoryId: 7,
    categoryName: "Pain",
    categoryColor: "800080",
    symptomsData: [
      SymptomsData(symptomName: "Pain free"),
      SymptomsData(symptomName: "Period cramps"),
      SymptomsData(symptomName: "Ovulation"),
      SymptomsData(symptomName: "Breast tenderness"),
      SymptomsData(symptomName: "Headache"),
      SymptomsData(symptomName: "Migraine"),
      SymptomsData(symptomName: "Migraine with aura"),
      SymptomsData(symptomName: "Lower back"),
      SymptomsData(symptomName: "Leg"),
      SymptomsData(symptomName: "Joint"),
    ],
  ),
  Symptoms(
    categoryId: 8,
    categoryName: "Vaginal Discharge",
    categoryColor: "0000FF",
    isVisibleCategory: 0,
    symptomsData: [
      SymptomsData(symptomName: "No discharge"),
      SymptomsData(symptomName: "Creamy"),
      SymptomsData(symptomName: "Watery"),
      SymptomsData(symptomName: "Unusual"),
      SymptomsData(symptomName: "Spotting"),
      SymptomsData(symptomName: "Sticky"),
      SymptomsData(symptomName: "Egg white"),
      SymptomsData(symptomName: "Gray"),
    ],
  ),
  Symptoms(
    categoryId: 9,
    categoryName: "Digestion",
    categoryColor: "FF0000",
    symptomsData: [
      SymptomsData(symptomName: "OK"),
      SymptomsData(symptomName: "Gassy"),
      SymptomsData(symptomName: "Bloating"),
      SymptomsData(symptomName: "Heartburn"),
      SymptomsData(symptomName: "Nauseous"),
      SymptomsData(symptomName: "Vomiting"),
    ],
  ),
  Symptoms(
    categoryId: 10,
    categoryName: "Activity",
    categoryColor: "8B0000",
    symptomsData: [
      SymptomsData(symptomName: "Yoga"),
      SymptomsData(symptomName: "Running"),
      SymptomsData(symptomName: "Gym"),
      SymptomsData(symptomName: "Swimming"),
      SymptomsData(symptomName: "Cycling"),
      SymptomsData(symptomName: "Walking"),
      SymptomsData(symptomName: "Pilates"),
      SymptomsData(symptomName: "Strength training"),
      SymptomsData(symptomName: "Stretching"),
      SymptomsData(symptomName: "Rest day"),
      SymptomsData(symptomName: "Meditation"),
    ],
  ),
  Symptoms(
    categoryId: 11,
    categoryName: "Cravings",
    categoryColor: "A52A2A",
    symptomsData: [
      SymptomsData(symptomName: "Sweet"),
      SymptomsData(symptomName: "Salty"),
      SymptomsData(symptomName: "Greasy"),
      SymptomsData(symptomName: "Spicy"),
      SymptomsData(symptomName: "Carbs"),
    ],
  ),
  Symptoms(
    categoryId: 12,
    categoryName: "Tests",
    categoryColor: "0000FF",
    symptomsData: [
      SymptomsData(symptomName: "Don't take test"),
      SymptomsData(symptomName: "Negative"),
      SymptomsData(symptomName: "Positive"),
    ],
  ),
  Symptoms(
    categoryId: 13,
    categoryName: "Ailments",
    categoryColor: "FFA500",
    symptomsData: [
      SymptomsData(symptomName: "Cold or flu"),
      SymptomsData(symptomName: "Allergy"),
      SymptomsData(symptomName: "Fever"),
      SymptomsData(symptomName: "UTI"),
      SymptomsData(symptomName: "STI"),
    ],
  ),
  Symptoms(
    categoryId: 14,
    categoryName: "Appointments",
    categoryColor: "800080",
    symptomsData: [
      SymptomsData(symptomName: "GYN"),
      SymptomsData(symptomName: "PAP smear"),
      SymptomsData(symptomName: "STI check-up"),
      SymptomsData(symptomName: "General check-up"),
      SymptomsData(symptomName: "Vaccination"),
    ],
  ),
  Symptoms(
    categoryId: 15,
    categoryName: "Birth control pill",
    categoryColor: "0000FF",
    symptomsData: [
      SymptomsData(symptomName: "Taken"),
      SymptomsData(symptomName: "Missed"),
      SymptomsData(symptomName: "Late"),
      SymptomsData(symptomName: "Double dose"),
      SymptomsData(symptomName: "Vaccination"),
    ],
  ),
  Symptoms(
    categoryId: 16,
    categoryName: "IUD",
    categoryColor: "FF0000",
    symptomsData: [
      SymptomsData(symptomName: "Thread checked"),
      SymptomsData(symptomName: "Inserted"),
      SymptomsData(symptomName: "Removed"),
    ],
  ),
  Symptoms(
    categoryId: 17,
    categoryName: "Supplements",
    categoryColor: "8B0000",
    symptomsData: [
      SymptomsData(symptomName: "Multivitamin"),
      SymptomsData(symptomName: "Magnesium"),
      SymptomsData(symptomName: "Iron"),
      SymptomsData(symptomName: "Vitamin D"),
      SymptomsData(symptomName: "Calcium"),
      SymptomsData(symptomName: "Folic acid"),
      SymptomsData(symptomName: "Prenatal vitamins"),
    ],
  ),
  Symptoms(
    categoryId: 18,
    categoryName: "Urine",
    categoryColor: "0000FF",
    symptomsData: [
      SymptomsData(symptomName: "Frequent urination"),
      SymptomsData(symptomName: "Burning sensation"),
      SymptomsData(symptomName: "Leaks or dribbles"),
    ],
  ),
  Symptoms(
    categoryId: 19,
    categoryName: "Other",
    categoryColor: "c336a7",
    symptomsData: [
      SymptomsData(symptomName: "Travel"),
      SymptomsData(symptomName: "Stress"),
      SymptomsData(symptomName: "Alcohol"),
      SymptomsData(symptomName: "Journaling"),
    ],
  ),
];

/// 2024-06-20
var defaultDateFormat = DateFormat('yyyy-MM-dd');

/// 2024-06-20 12:20:11
var currentDateFormat = DateFormat('yyyy-MM-dd hh:mm:ss');
